version: '3.1'

services:

  restful-api-yt:
    image: node:20.11.1
    environment:
      SECRET: ${SECRET}
      USER_DATABASE: ${USER_DATABASE}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE}
      DATABASE: ${DATABASE}
      HOST_DATABASE: 'host.docker.internal'
      PORT_DATABASE: ${PORT_DATABASE}
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: >
      sh -c "
        apk add --no-cache make gcc g++ python
        npm install 
        npm rebuild bcrypt --build-from-source
        apk del make gcc g++ python
        npm start
      "
