version: '3.1'

services:
  restful-api-yt:
    image: node:20.11.1
    environment:
      SECRET: ${SECRET}
      USER_DATABASE: ${USER_DATABASE}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE}
      DATABASE: ${DATABASE}
      HOST_DATABASE: ${HOST_DATABASE}
      PORT_DATABASE: ${PORT_DATABASE}
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    ports:
      - "4000:4000"

  mariadb:
    image: mariadb:11.0
    restart: always
    environment:
      MARIADB_USER: ${USER_DATABASE}
      MARIADB_ROOT_PASSWORD: ${PASSWORD_DATABASE}
      MARIADB_DATABASE: ${DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080